import type {
  Manifest,
  DeployResult,
  DeployedContract,
} from '../../shared/types'

/** Fetch the deployable + connectable contract catalog. */
export async function fetchCatalog(): Promise<Manifest[]> {
  const res = await fetch('/api/contracts')
  if (!res.ok) throw new Error(`Catalog failed: ${res.status}`)
  const data = (await res.json()) as { contracts: Manifest[] }
  return data.contracts
}

/** Deploy a configurable contract to testnet with the given config.
 *  When deployerSecret is provided the user's wallet signs the deploy and
 *  becomes the contract owner — the {{deployer}} sentinel resolves to it. */
export async function deployContract(
  manifestId: string,
  config: Record<string, unknown>,
  deployerSecret?: string,
): Promise<DeployResult> {
  const body: Record<string, unknown> = { manifestId, config }
  if (deployerSecret) body.deployerSecret = deployerSecret
  const res = await fetch('/api/deploy', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body),
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data.error ?? `Deploy failed: ${res.status}`)
  return data as DeployResult
}

/**
 * Generate `src/contracts.ts` for the user's app — a typed registry of the
 * contract IDs deployed for this project, so the generated dApp can call them.
 */
export function buildContractsFile(contracts: DeployedContract[]): string {
  const entries = contracts
    .map(
      (c) => `  ${JSON.stringify(c.manifestId)}: {
    name: ${JSON.stringify(c.name)},
    category: ${JSON.stringify(c.category)},
    contractId: ${JSON.stringify(c.contractId)},
    owner: ${JSON.stringify((c.config?.owner as string) ?? c.deployer ?? '')},
    explorerUrl: ${JSON.stringify(c.explorerUrl)},
  },`,
    )
    .join('\n')

  // A funded account that exists on-chain, used only as the source for
  // read-only simulations (so reads work before a wallet is connected).
  const viewSource = contracts.find((c) => c.deployer)?.deployer ?? ''

  return `// Auto-generated by xlmcode. Do not edit by hand.
// Contracts deployed to Stellar testnet for this project.
export const NETWORK = 'testnet' as const
export const RPC_URL = 'https://soroban-testnet.stellar.org' as const
export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015' as const

// Funded source for read-only contract simulations (no signing).
export const VIEW_SOURCE = ${JSON.stringify(viewSource)}

export const CONTRACTS = {
${entries}
} as const

export type ContractKey = keyof typeof CONTRACTS
`
}

/** Path of the injected registry inside the generated app's file tree. */
export const CONTRACTS_FILE = '/contracts.ts'
